import jsPDF from 'jspdf';

export interface TaxPDFData {
  annualSalary: number;
  maritalStatus: string;
  isSsf: boolean;
  lifeInsurance: number;
  healthInsurance: number;
  annualTax: number;
  monthlyTax: number;
  monthlyInhand: number;
  effectiveRate: number;
  slabs: { range: string; rate: number; taxableAmount: number; taxAmount: number }[];
}

export function generateTaxReportPDF(data: TaxPDFData): void {
  const doc = new jsPDF();

  // Header banner
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, 210, 40, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('SAARTHI CIVIC DIGITAL PLATFORM', 14, 18);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(226, 232, 240);
  doc.text('Nepal Income Tax Estimation Statement (FY 2083/84)', 14, 28);

  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text(`Generated Date: ${new Date().toLocaleString()}`, 14, 35);

  // Summary box
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(14, 48, 182, 45, 3, 3, 'FD');

  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text('Tax Overview & Summary', 20, 58);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Annual Gross Salary: Rs. ${data.annualSalary.toLocaleString()}`, 20, 68);
  doc.text(`Status: ${data.maritalStatus.toUpperCase()} | SSF: ${data.isSsf ? 'Yes' : 'No'}`, 20, 76);
  doc.text(`Total Deductions Claimed: Rs. ${(data.lifeInsurance + data.healthInsurance).toLocaleString()}`, 20, 84);

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(225, 29, 72); // rose-600
  doc.text(`Total Annual Income Tax: Rs. ${data.annualTax.toLocaleString()}`, 110, 68);
  doc.setTextColor(217, 119, 6); // amber-600
  doc.text(`Monthly TDS Deduction: Rs. ${data.monthlyTax.toLocaleString()}`, 110, 76);
  doc.setTextColor(16, 185, 129); // emerald-600
  doc.text(`Monthly Net In-Hand: Rs. ${data.monthlyInhand.toLocaleString()}`, 110, 84);

  // Slab Breakdown Header
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text('Detailed Tax Slab Breakdown', 14, 106);

  // Table header
  let startY = 114;
  doc.setFillColor(30, 41, 59);
  doc.rect(14, startY, 182, 8, 'F');

  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.text('Slab Bracket', 18, startY + 6);
  doc.text('Rate', 85, startY + 6);
  doc.text('Taxable Amount (NPR)', 115, startY + 6);
  doc.text('Tax Amount (NPR)', 160, startY + 6);

  // Table rows
  startY += 8;
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(51, 65, 85);

  data.slabs.forEach((slab, index) => {
    const rowY = startY + index * 9;
    if (index % 2 === 0) {
      doc.setFillColor(241, 245, 249);
      doc.rect(14, rowY, 182, 9, 'F');
    }
    doc.text(slab.range, 18, rowY + 6);
    doc.text(`${slab.rate}%`, 85, rowY + 6);
    doc.text(`Rs. ${slab.taxableAmount.toLocaleString()}`, 115, rowY + 6);
    doc.text(`Rs. ${slab.taxAmount.toLocaleString()}`, 160, rowY + 6);
  });

  const finalY = startY + data.slabs.length * 9 + 15;

  // Footer notes
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text('Note: This document is an automated estimation generated by SAARTHI Platform based on IRD Nepal standards.', 14, finalY);
  doc.text('Official tax filing must be completed through the Inland Revenue Department portal (ird.gov.np).', 14, finalY + 5);

  doc.save(`SAARTHI_Income_Tax_Report_${data.annualSalary}.pdf`);
}

export interface BluebookPDFData {
  province: string;
  vehicleType: string;
  engineCc: number;
  renewalMonthsLate: number;
  baseTax: number;
  penaltyPercent: number;
  penaltyAmount: number;
  thirdPartyInsurance: number;
  totalPayable: number;
}

export function generateBluebookReceiptPDF(data: BluebookPDFData): void {
  const doc = new jsPDF();

  // Header banner
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, 210, 40, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('SAARTHI VEHICLE BLUEBOOK STATEMENT', 14, 18);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(226, 232, 240);
  doc.text(`Province Transport Tax Calculation Statement (${data.province})`, 14, 28);

  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text(`Generated Date: ${new Date().toLocaleString()}`, 14, 35);

  // Statement Box
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(14, 48, 182, 80, 3, 3, 'FD');

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text('Vehicle Specification & Breakdown', 20, 58);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Selected Province: ${data.province}`, 20, 68);
  doc.text(`Vehicle Category: ${data.vehicleType.toUpperCase()}`, 20, 76);
  doc.text(`Engine Capacity / Rating: ${data.engineCc} CC / kW`, 20, 84);
  doc.text(`Late Renewal Delay: ${data.renewalMonthsLate} month(s)`, 20, 92);

  doc.line(20, 98, 190, 98);

  doc.text(`Base Vehicle Tax: Rs. ${data.baseTax.toLocaleString()}`, 20, 106);
  doc.text(`Late Renewal Penalty (${data.penaltyPercent}%): Rs. ${data.penaltyAmount.toLocaleString()}`, 20, 114);
  doc.text(`Third-Party Insurance (Est.): Rs. ${data.thirdPartyInsurance.toLocaleString()}`, 20, 122);

  // Total callout
  doc.setFillColor(15, 23, 42);
  doc.rect(14, 134, 182, 16, 'F');
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(52, 211, 153); // emerald-400
  doc.text(`Total Estimated Tax & Charges: Rs. ${data.totalPayable.toLocaleString()}`, 20, 144);

  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text('Note: Verification and payment should be carried out at your regional Transport Management Office (Yatayat Office).', 14, 162);

  doc.save(`SAARTHI_Bluebook_Tax_Estimate_${data.province}_${data.vehicleType}.pdf`);
}

export interface ReceiptPDFData {
  merchantName: string;
  date: string;
  totalAmount: number;
  taxAmount: number;
  category: string;
  items?: { name: string; price: number }[];
  summaryNotes?: string;
}

export function generateReceiptPDF(data: ReceiptPDFData): void {
  const doc = new jsPDF();

  // Header banner
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, 210, 40, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('SAARTHI CIVIC DIGITAL PLATFORM', 14, 18);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(226, 232, 240);
  doc.text('Scanned Expense & Purchase Receipt Statement', 14, 28);

  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text(`Generated Date: ${new Date().toLocaleString()}`, 14, 35);

  // Statement Box
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(14, 48, 182, 52, 3, 3, 'FD');

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text(data.merchantName || 'Merchant Expense Receipt', 20, 58);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Transaction Date: ${data.date || 'N/A'}`, 20, 68);
  doc.text(`Expense Category: ${data.category || 'General'}`, 20, 76);
  if (data.summaryNotes) {
    doc.text(`Notes: ${data.summaryNotes}`, 20, 84);
  }

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(16, 185, 129);
  doc.text(`Total Amount Paid: Rs. ${data.totalAmount ? data.totalAmount.toLocaleString() : '0'}`, 110, 68);
  doc.setTextColor(217, 119, 6);
  doc.text(`VAT / Tax Included: Rs. ${data.taxAmount ? data.taxAmount.toLocaleString() : '0'}`, 110, 76);

  // Itemized breakdown if available
  let finalY = 112;
  if (data.items && data.items.length > 0) {
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    doc.text('Itemized Purchased Goods & Services', 14, 112);

    let startY = 118;
    doc.setFillColor(30, 41, 59);
    doc.rect(14, startY, 182, 8, 'F');

    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(255, 255, 255);
    doc.text('Item Description', 18, startY + 6);
    doc.text('Price (NPR)', 160, startY + 6);

    startY += 8;
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(51, 65, 85);

    data.items.forEach((item, index) => {
      const rowY = startY + index * 8;
      if (index % 2 === 0) {
        doc.setFillColor(241, 245, 249);
        doc.rect(14, rowY, 182, 8, 'F');
      }
      doc.text(item.name, 18, rowY + 5.5);
      doc.text(`Rs. ${item.price.toLocaleString()}`, 160, rowY + 5.5);
    });

    finalY = startY + data.items.length * 8 + 15;
  }

  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text('Note: Digitally processed expense receipt statement from SAARTHI Digital Receipt Engine.', 14, finalY);

  doc.save(`SAARTHI_Receipt_${(data.merchantName || 'Expense').replace(/[^a-zA-Z0-9]/g, '_')}.pdf`);
}
